/* SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause */
#ifndef _DT_BINDINGS_LPDDR2_H
#define _DT_BINDINGS_LPDDR2_H

#define LPDDR2_MANID_SAMSUNG		1
#define LPDDR2_MANID_QIMONDA		2
#define LPDDR2_MANID_ELPIDA		3
#define LPDDR2_MANID_ETRON		4
#define LPDDR2_MANID_NANYA		5
#define LPDDR2_MANID_HYNIX		6
#define LPDDR2_MANID_MOSEL		7
#define LPDDR2_MANID_WINBOND		8
#define LPDDR2_MANID_ESMT		9
#define LPDDR2_MANID_SPANSION		11
#define LPDDR2_MANID_SST		12
#define LPDDR2_MANID_ZMOS		13
#define LPDDR2_MANID_INTEL		14
#define LPDDR2_MANID_NUMONYX		254
#define LPDDR2_MANID_MICRON		255

#define LPDDR2_TYPE_S4			0
#define LPDDR2_TYPE_S2			1
#define LPDDR2_TYPE_NVM			2

#endif /*_DT_BINDINGS_LPDDR2_H */
